name: IntellectualSites

on: workflow_dispatch

jobs:
  PlotSquared:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "IntellectualSites/PlotSquared"
      name: "PlotSquared"
      target: "Bukkit/build/libs/*.jar"

