name: Photon

on: workflow_dispatch

jobs:
  AntiCheatAddition:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Photon-GitHub/AntiCheatAddition"
      name: "AntiCheatAddition"
      java: 17
      tasks: "clean package -DskipTests"

