name: Pyrbu

on: workflow_dispatch

jobs:
  ZNPCsPlus:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Pyrbu/ZNPCsPlus"
      name: "ZNPCsPlus"
      java: "17"
      target: "plugin/build/libs/*.jar"

